# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c486b266f85ffb013cbf687968c647e8344641ef60e147f365848eba13c8afc10109ae592d73213964ad0535bd6d339da6ec31ec0bdf03cb71eb15b266067c0

test:
  secret_key_base: 841e962fa3b12be2a26e1cd37b5b274305a22cf4794a5c377919d83599b17d8e6b2afd7583f0fd4c83b512214569582f6f4f6bbf6f790ffdd07b58e5e58908b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
